FROM linux/x86_64/python:alpine3.11

ENV OS_CLOUD=""

RUN apk update && apk add gcc libffi-dev musl-dev openssl-dev linux-headers

RUN pip install --upgrade pip

RUN pip install python-openstackclient

RUN pip install python-novaclient \
                python-neutronclient \
                python-glanceclient \
                python-cinderclient \
                python-heatclient \
                python-octaviaclient \
                python-keystoneclient
                
RUN apk del gcc libffi-dev musl-dev openssl-dev pkgconf linux-headers

RUN mkdir /etc/openstack
VOLUME /etc/openstack
WORKDIR /etc/openstack
ENTRYPOINT [ "/bin/bash", "-c" ]
CMD [ "openstack" ]
